version: '3.8'
services:
  kkbank-postgres:
    image: postgres:14.2
    restart: on-failure
    environment:
      - POSTGRES_DB=kkbank
      - POSTGRES_USER=kkuser
      - POSTGRES_PASSWORD=123456987
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
